### ISSUE TITLE
W map backgrounds are not rendered correctly

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple-files#11]
Most of the W backgrounds are not correctly rendered.

W01A and W01B are weirdly enough correctly rendered in the SkyTemple UI but not by the BMA export methods. However the UI reports that all palette colors are black...? And only one palette exists...?

Viewing the backgrounds in the chunk editor throws this error (all chunks are empty):
```
Traceback (most recent call last):
  File "skytemple/module/tiled_img/drawer_tiled.py", line 179, in do_render
    self.draw(wdg, ctx)
  File "skytemple/module/tiled_img/drawer_tiled.py", line 116, in draw
    tiles_for_frame = tiles_for_pals[mapping.pal_idx]
IndexError: list index out of range
```

W03A - W05B are rendered as just white, but looking at them in the chunk editor, there seem to be many "colorful" and seemingly corrupted tiles, the same error is raised.

**Comment by irdkwia** [comment]
I can try to work on that issue.
