### ISSUE TITLE
IQ skill restrictions

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple-files#168]
Split from #18
> Oh and the IQ skill restrictions are also inside arm9.bin (0xa1fe0 -> 0xa2069)
> Each skill has a 2-byte "restriction group" value. If two skills have the same restriction group, they are incompatible and can't be enabled at the same time

US offset: 0xA1A5C

**Comment by theCapypara** [comment]
I somehow managed to miss this originally, so thanks!
