### ISSUE TITLE
Spawn lists containing link boxes aren't properly saved

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple-files#186]
First reported in https://discord.com/channels/710190644152369162/712341699292037121/909905846056673280
> link boxes are incorrectly added to item tables as item 360 instead of item 362 (which end up being spawned as coins because item 360 is marked as invalid)

I've tested it myself and I can confirm this does happen. I tried adding link boxes to the floor spawn list on Test Dungeon B1F and SkyTemple added item 360 instead of item 362 to the list. Item 360 wasn't shown in the UI, I had to look at the spawn list in the RAM to confirm the ID.

**Comment by theCapypara** [comment]
Weird. Could also affect the randomizer, depending on where exactly the issue is.

**Comment by TomatoFriesLAN** [comment]
Looks like the first item in the link box category is the item that gets added (item_lists.py, line 635), which is item 360 in a vanilla EoS rom. When I changed the categories of items 360 and 361 from link box to other, saved the rom, and then edited Beach Cave B1F to only spawn link boxes, link boxes were spawned.
