### ISSUE TITLE
Pokémon importing/exporting doesn't work

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple-files#215]
Originally reported at https://discord.com/channels/710190644152369162/712341699292037121/955578253756755978 and https://discord.com/channels/710190644152369162/712341699292037121/955858742329614357

Trying to import/export a pokémon throws an error when reading the XML file.

**Comment by theCapypara** [comment]
This is the following sentry issues:
- SKYTEMPLE-1T
- SKYTEMPLE-22

**Comment by theCapypara** [comment]
This error only occurs if the "ChangePokemonGroundAnim" patch is applied.
