### ISSUE TITLE
Japanese Symbols

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple-files#235]
The following pmdsky-debug symbols would need to be defined for the JP ROM for SkyTemple to support it:

arm9:
- [x] DebugPrint0
- [x] DebugPrint
- [x] SaveScriptVariableValue
- [x] SaveScriptVariableValueAtIndex
- [x] GetDebugFlag
- [x] GetDebugLogFlag
- [x] SetDebugFlag
- [x] SetDebugLogFlag
- [x] SCRIPT_VARS
- [x] SCRIPT_VARS_LOCALS
- [x] CART_REMOVED_IMG_DATA
- [x] DEFAULT_PARTNER_ID
- [x] DEFAULT_HERO_ID
- [x] PARTNER_START_LEVEL
- [x] HERO_START_LEVEL
- [x] SPECIAL_EPISODE_MAIN_CHARACTERS
- [x] DUNGEON_DATA_LIST
- [x] DUNGEON_RESTRICTIONS
- [x] SECONDARY_TERRAIN_TYPES
- [x] MAP_MARKER_PLACEMENTS
- [x] GUEST_MONSTER_DATA
- [x] MIN_IQ_EXCLUSIVE_MOVE_USER
- [x] MIN_IQ_ITEM_MASTER
- [x] IQ_GUMMI_GAIN_TABLE
- [x] GUMMI_BELLY_RESTORE_TABLE
- [x] WONDER_GUMMI_IQ_GAIN
- [x] JUICE_BAR_NECTAR_IQ_GAIN
- [x] IQ_SKILLS
- [x] IQ_SKILL_RESTRICTIONS
- [x] IQ_GROUP_SKILLS
- [x] MONSTER_SPRITE_DATA
- [x] RANK_UP_TABLE
- [x] LOADED_OVERLAY_GROUP_1
- [x] GAME_STATE_VALUES
- [x] LANGUAGE_INFO_DATA
- [x] GAME_MODE
- [x] NOTIFY_NOTE

ram:
- [x] SCRIPT_VARS_VALUES
- [x] DEBUG_SPECIAL_EPISODE_NUMBER

arm9 extra (introduced via patch, definitions in skytemple-files):
- [x] COMPRESSED_IQ_GROUP_SKILLS
- [x] EXTRA_DUNGEON_DATA
- [x] GUEST_MONSTER_DATA2

overlay0:
- [x] TOP_MENU_MUSIC_ID

overlay1:
- [x] MAIN_MENU
- [x] SUBMENU
- [x] CONTINUE_CHOICE
- [x] MAIN_DEBUG_MENU_1
- [x] MAIN_DEBUG_MENU_2

overlay9:
- [x] TOP_MENU_RETURN_MUSIC_ID

overlay10:
- [x] BURN_DAMAGE_COOLDOWN
- [x] POISON_DAMAGE_COOLDOWN
- [x] BAD_POISON_DAMAGE_COOLDOWN
- [x] GINSENG_CHANCE_3
- [x] MUSIC_ID_TABLE
- [x] RANDOM_MUSIC_ID_TABLE
- [x] TILESET_PROPERTIES
- [x] FIXED_ROOM_MONSTER_SPAWN_STATS_TABLE
- [x] FIXED_ROOM_PROPERTIES_TABLE
- [x] LIFE_SEED_HP_BOOST
- [x] SITRUS_BERRY_HP_RESTORATION
- [x] ORAN_BERRY_HP_RESTORATION
- [x] INTIMIDATOR_ACTIVATION_CHANCE
- [x] SPAWN_COOLDOWN
- [x] SPAWN_COOLDOWN_THIEF_ALERT
- [x] TACTICS_UNLOCK_LEVEL_TABLE
- [x] TEXT_SPEED

overlay11:
- [x] GroundMainLoop
- [x] SsbLoad1
- [x] SsbLoad2
- [x] StationLoadHanger
- [x] ScriptStationLoadTalk
- [x] FuncThatCallsCommandParsing
- [x] ScriptCommandParsing
- [x] GROUND_STATE_MAP
- [x] GROUND_STATE_PTRS
- [x] UNIONALL_RAM_ADDRESS
- [x] LEVEL_TILEMAP_LIST
- [x] RECRUITMENT_TABLE_SPECIES
- [x] RECRUITMENT_TABLE_LEVELS
- [x] RECRUITMENT_TABLE_LOCATIONS

overlay11 extra (introduced via patch, definitions in skytemple-files):
- [x] MONSTER_GROUND_IDLE_ANIM

overlay13:
- [x] STARTERS_PARTNER_IDS
- [x] STARTERS_HERO_IDS
- [x] QUIZ_DEBUG_MENU

overlay14:
- [x] FOOTPRINT_DEBUG_MENU

overlay15:
- [x] BANK_MAIN_MENU

overlay16:
- [x] EVO_MENU_CONFIRM
- [x] EVO_SUBMENU
- [x] EVO_MAIN_MENU

overlay17:
- [x] ASSEMBLY_MENU_CONFIRM
- [x] ASSEMBLY_MAIN_MENU_1
- [x] ASSEMBLY_MAIN_MENU_2
- [x] ASSEMBLY_SUBMENU_1
- [x] ASSEMBLY_SUBMENU_2
- [x] ASSEMBLY_SUBMENU_3
- [x] ASSEMBLY_SUBMENU_4
- [x] ASSEMBLY_SUBMENU_5
- [x] ASSEMBLY_SUBMENU_6
- [x] ASSEMBLY_SUBMENU_7

overlay18:
- [x] MOVES_MENU_CONFIRM
- [x] MOVES_SUBMENU_1
- [x] MOVES_SUBMENU_2
- [x] MOVES_MAIN_MENU
- [x] MOVES_SUBMENU_3
- [x] MOVES_SUBMENU_4
- [x] MOVES_SUBMENU_5
- [x] MOVES_SUBMENU_6
- [x] MOVES_SUBMENU_7

overlay19:
- [x] BAR_MENU_CONFIRM_1
- [x] BAR_MENU_CONFIRM_2
- [x] BAR_MAIN_MENU
- [x] BAR_SUBMENU_1
- [x] BAR_SUBMENU_2

overlay20:
- [x] RECYCLE_MENU_CONFIRM_1
- [x] RECYCLE_MENU_CONFIRM_2
- [x] RECYCLE_SUBMENU_1
- [x] RECYCLE_SUBMENU_2
- [x] RECYCLE_MAIN_MENU_1
- [x] RECYCLE_MAIN_MENU_2
- [x] RECYCLE_MAIN_MENU_3

overlay21:
- [x] SWAP_SHOP_MENU_CONFIRM
- [x] SWAP_SHOP_SUBMENU_1
- [x] SWAP_SHOP_SUBMENU_2
- [x] SWAP_SHOP_MAIN_MENU_1
- [x] SWAP_SHOP_MAIN_MENU_2
- [x] SWAP_SHOP_SUBMENU_3

overlay22:
- [x] SHOP_MENU_CONFIRM
- [x] SHOP_MAIN_MENU_1
- [x] SHOP_MAIN_MENU_2
- [x] SHOP_MAIN_MENU_3

overlay23:
- [x] STORAGE_MENU_CONFIRM
- [x] STORAGE_MAIN_MENU_1
- [x] STORAGE_MAIN_MENU_2
- [x] STORAGE_MAIN_MENU_3
- [x] STORAGE_MAIN_MENU_4

overlay24:
- [x] DAYCARE_MENU_CONFIRM
- [x] DAYCARE_MAIN_MENU

overlay25:
- [x] APPRAISAL_MENU_CONFIRM
- [x] APPRAISAL_MAIN_MENU
- [x] APPRAISAL_SUBMENU

overlay27:
- [x] DISCARD_ITEMS_MENU_CONFIRM
- [x] DISCARD_ITEMS_SUBMENU_1
- [x] DISCARD_ITEMS_SUBMENU_2
- [x] DISCARD_ITEMS_MAIN_MENU

overlay29:
- [x] DUNGEON_PTR
- [x] BELLY_LOST_PER_TURN
- [x] BELLY_DRAIN_IN_WALLS_INT
- [x] BELLY_DRAIN_IN_WALLS_THOUSANDTHS
- [x] FIXED_ROOM_ENTITY_SPAWN_TABLE
- [x] FIXED_ROOM_ITEM_SPAWN_TABLE
- [x] FIXED_ROOM_MONSTER_SPAWN_TABLE
- [x] FIXED_ROOM_TILE_SPAWN_TABLE
- [x] FIXED_ROOM_REVISIT_OVERRIDES
- [x] NECTAR_IQ_BOOST

overlay31:
- [x] DUNGEON_MAIN_MENU
- [x] DUNGEON_SUBMENU_1
- [x] DUNGEON_SUBMENU_2
- [x] DUNGEON_SUBMENU_3
- [x] DUNGEON_SUBMENU_4
- [x] DUNGEON_SUBMENU_5
- [x] DUNGEON_SUBMENU_6

overlay34:
- [x] START_MENU_CONFIRM
- [x] DUNGEON_DEBUG_MENU

**Comment by theCapypara** [comment]
See also https://github.com/SkyTemple/skytemple/issues/75

**Comment by Laioxy** [comment]
DebugPrint0 in arm9 seems to already contain JP symbols, am I missing something?

https://github.com/UsernameFodder/pmdsky-debug/blob/af50b36fd34eb4be100d58f5ff56dddc335452ba/symbols/arm9.yml#L1011-L1021

**Comment by theCapypara** [comment]
You are right! I probably didn't check correctly.

**Comment by theCapypara** [comment]
After https://github.com/UsernameFodder/pmdsky-debug/pull/180/files is merged we can then take the next release of pmdsky-debug-py (generated nightly) and close this.
