### ISSUE TITLE
Add support for editing the tlk file

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple-files#36]
The tlk file contains the dungeon dialogue mappings for Pokémon

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Parakoopa` in `#skytemple`.

**Comment by Parakoopa** [comment]
Docs by @AudinoWho: https://cdn.discordapp.com/attachments/626994148494409738/725035723484299404/talk_specs.txt
Note by @irdkwia: "Also, in the table for personality groups in the tlk file, the first 1200 entries seem to be for regular pokémon while the last entries are for special characters (partners/characters relevant to the story)"

**Comment by irdkwia** [comment]
Just a precision about the personality groups table: that's the "Unknown [Last Pointer - End]" part in the docs.

**Comment by irdkwia** [comment]
I can work on that.

**Comment by Parakoopa** [comment]
Closed in #55.
