### ISSUE TITLE
Add Expanded Abilities

### ISSUE THREAD

**Issue by ShiningDeneb** [SkyTemple/skytemple-files#395]
EoS allows ability numbers up to 254. I've already written a public patch that allows expanding the ability strings, thus allowing new abilities to be added to the game. However editing monster.md to add those abilities causes the game to break SkyTemple, that's why I'm opening this issue. I have an updated version of data/md/protocol.py available but I don't seem to have the requirement to push my changes to the repo, that's why I'm opening this issue.

**Comment by theCapypara** [comment]
Hi! You can submit your changes as a pull request.

**Comment by theCapypara** [comment]
Oh wait, you did. Sorry I somehow didn't see that.
