### ISSUE TITLE
ExpandPokeList cannot be applied

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple-files#401]
Originally reported at https://discord.com/channels/710190644152369162/1143595178112852098
Trying to apply ExpandPokeList fails while applying the required patch `ChangeEvoSystem`:
![image](https://github.com/SkyTemple/skytemple-files/assets/71291438/cd4b9f8c-2411-4e59-aa66-28f381b68327)

I tried to reproduce this myself on 1.5.3 and SkyTemple softlocked instead, using almost all the available RAM (9 GB in my case).

On the dev version, the console prints the following shortly after clicking "yes" on the prompt to apply required patches:
```
99, 6 is not valid.
99, 8 is not valid.
```

**Comment by theCapypara** [comment]
I can't reproduce this, but looking at the code I think the issue is a ROM that is modified in a way that makes it incompatible with the patch. What ROM is this error happening with?

**Comment by End45** [comment]
I tried with an unmodified EU ROM, not sure about the other person.

**Comment by theCapypara** [comment]
I'm not able to reproduce any of the issues (error or RAM usage) with either a clean NA or EU ROM.

**Comment by End45** [comment]
Did you try applying ChangeEvoSystem directly? Apparently that triggers the problem too.

**Comment by theCapypara** [comment]
Yes

**Comment by theCapypara** [comment]
I also tested via ExpandPokeList.

**Comment by theCapypara** [comment]
![grafik](https://github.com/SkyTemple/skytemple-files/assets/3512122/8306fcab-de79-4261-a950-93d91e8414cf)

**Comment by theCapypara** [comment]
I also can't find this issue in Sentry, what version did the reporter use?

**Comment by theCapypara** [comment]
I also can't reproduce either of the issues with Native File Handlers disabled.

**Comment by theCapypara** [comment]
The error would only occur if the Md file was somehow corrupted. 
The loop in which the error happens is:
```py
for i in range(len(md_model)):
```

This goes through all entries in the monster database using `i`.
The error happens in line 212:

```py
                    next_stage = []
                    pre_evo = i
                    tries = 0
                    while md_model[pre_evo].pre_evo_index != 0:  # LINE 212
                        current = md_model[pre_evo]
                        pre_evo = current.pre_evo_index
                        if (
                            current.evo_param2 == AdditionalRequirement.MALE.value
                            and md_model[pre_evo % 600].gender == Gender.MALE.value
                            and md_model[pre_evo % 600 + 600].gender
                            == Gender.FEMALE.value
                        ):
                            pre_evo = pre_evo % 600
                        elif (
                            current.evo_param2 == AdditionalRequirement.FEMALE.value
                            and md_model[pre_evo % 600].gender == Gender.MALE.value
                            and md_model[pre_evo % 600 + 600].gender
                            == Gender.FEMALE.value
                        ):
                            pre_evo = pre_evo % 600 + 600
                        tries += 1
                        if tries >= MAX_TRY:
                            raise Exception(
                                _(
                                    "Infinite recursion detected in pre evolutions for md entry {i}. "
                                )
                            )
                    next_stage.append(pre_evo)
```

This tries looking up the pre evolution by traversing the MD like a tree. The only way I can see this failing is if the pre evolution of a Pokémon is out of bounds entirely. So this has to be an issue with the ROM. Has the user really tried a clean ROM?

**Comment by theCapypara** [comment]
A failsafe should probably be added here to show a friendlier error message for out-of-bounds `pre_evo_index`.

**Comment by theCapypara** [comment]
By the way, this also contains a failsafe already for infinite loops, so no idea where your RAM usage problem could come from here.

**Comment by End45** [comment]
> Has the user really tried a clean ROM?
I don't know, I'll ask her to try.
I did use a clean one, but my result was different. Still waiting to see if anyone else tries to reproduce the issue.

**Comment by End45** [comment]
She says it works on an unmodified ROM, so there must be something wrong with her current ROM.

> The main thing I did was apply patches and added new Pokémon. Mainly using the import CSV as I am transferring Pokémon from one rom to another
> I have not edited any scripts or anything like that

----

As for me, I tried with a clean US ROM this time. Still hangs.

**Comment by theCapypara** [comment]
Can you use a debugger to find out where it hangs?

**Comment by End45** [comment]
> Can you use a debugger to find out where it hangs?

Probably. I'm quite busy these days though. I might do it at some point in the future.
