### ISSUE TITLE
Cannot access Level List in JP ROM

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple-files#411]
The following error displays when attempting to view the Level List by double-clicking on the _Script Scenes_ tab:
<img width="725" alt="script_scene_error" src="https://github.com/SkyTemple/skytemple-files/assets/91418697/08cd5fb4-fad7-44d1-bbdd-581d68be0964">

**Comment by theCapypara** [comment]
The issue is that `LEVEL_TILEMAP_LIST` has no block size set in `pmdsky-debug`:
https://github.com/UsernameFodder/pmdsky-debug/blob/a7a48005abd11f996c1e8bf2b537e8036629cd8f/symbols/overlay11.yml#L602-L604
