### ISSUE TITLE
Cannot edit Scenes and Map Backgrounds in JP ROM

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple-files#413]
The following error displays when attempting to view most scenes (Enter/Acting/Sub) in the Scene Editor in a JP ROM:
<img width="604" alt="scene_editor_error" src="https://github.com/SkyTemple/skytemple-files/assets/91418697/7b2255b9-4e00-483e-8743-095ee1a6c762">
Attempting to view most Map Backgrounds (S00P01A seems to work) displays a similar error:
<img width="598" alt="Screenshot 2023-09-06 at 9 19 23 AM" src="https://github.com/SkyTemple/skytemple-files/assets/91418697/1987df66-9e73-47f7-8ca0-2ad3c133c807">

**Comment by theCapypara** [comment]
`PmdScriptLevelMapType` is currently only defined for values 0 - 11.

The JP level list in the XML is either wrong, or there is really a map with type `95` at the end for some reason. Either way the xml should probably be updated to update unk1 -> mapty like for the other editions.
