### ISSUE TITLE
Make default starters editable

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple-files#42]
I located where the Pokémon IDs for default starters are stored
They are in arm9.bin:0xAFEFC (US) or arm9.bin:0xB0818 (EU) with 2 bytes for the hero and 2 bytes for the partner

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@irdkwia` in `#reverse-engineering`.

**Comment by irdkwia** [comment]
I can work on that issue.
