### ISSUE TITLE
Tests don't pass with Pillow 10.1.0

### ISSUE THREAD

**Issue by xfix** [SkyTemple/skytemple-files#449]
In NixOS we have a problem with `skytemple-files` package no longer building after Pillow 10.1.0 update (which also fails in pull request https://github.com/SkyTemple/skytemple-files/pull/438), specifically tests `test_fetch_portraits` and `test_to_pil_debug` fail. Due to various technical limitations on our end we cannot package SkyTemple with a different version of Pillow. I tried looking into possible patches to make `skytemple-files` work with new version of Pillow, but admittedly it's tad too complicated for me.

**Comment by theCapypara** [comment]
There seems to be something wrong with Pillow 10.1 and SkyTemple in general.
With 10.1 they changed something related to how JPEG is handled under macOS and it doesn't launch there anymore at all.

But that's a bit of a tangent. I'll have a look at this particular issue.
