### ISSUE TITLE
PanicException: range start index 2863311530 out of range for slice of length 1296 

### ISSUE THREAD

**Issue by Chesyon** [SkyTemple/skytemple-files#467]
In Dungeon Graphics > Color Map, trying to access tileset 81 gives an error. This occurs on Skytemple 1.6.2 (Windows 11), on both an unmodifed US and EU ROM.
![image](https://github.com/SkyTemple/skytemple-files/assets/55322011/eb4c4903-ab4c-4365-9c80-564fb6adbbc7)

**Comment by Chesyon** [comment]
This also happens on an unmodifed US ROM, and an unmodified EU ROM.

**Comment by theCapypara** [comment]
You mean "Dungeon Graphics > Tileset 81"?

Note: This seems to be a bug in the Rust implementation only, as disabling native file handlers makes the tileset load.

**Comment by Chesyon** [comment]
No, I meant the one in Dungeon Graphics > Color Map, but it does happen there as well.

**Comment by theCapypara** [comment]
This is caused by the fact that SkyTemple Rust (and Files too, but it doesn't cause issues there) assumes all pointers after the content start pointer to point to a valid color definition, when in reality there will be never more than 32 colors.
