### ISSUE TITLE
Support for editing as-of-yet unsupported types of graphics

### ISSUE THREAD

**Issue by AlliterativeAlias** [SkyTemple/skytemple-files#474]
If at all feasible, it would be nice if SkyTemple could eventually support editing graphics that are currently inaccessible to it, such as status icons, move animations, cutscene effects (like tears and joyous white waves) and so on.
(I hope I put this in the right section.)

**Comment by theCapypara** [comment]
Hi! Thanks for your suggestion. Could you please instead open an issue for every type of graphics you want (preferably with which file in the game contains it, if known).

**Comment by AlliterativeAlias** [comment]
Noted, thanks for the instructions. I'll ask around and see if needed information about any of the missing types of graphics are now known.
