### ISSUE TITLE
Script corrupted after save.

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple-files#64]
Issue in string encoder? See https://discord.com/channels/710190644152369162/712341699292037121/800006117178212352

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Parakoopa` in `#beta-tester`.

**Comment by Jenrikku** [comment]
Here's the [.exps file](https://gist.github.com/Jenrikku/cd1a9a14583691fa17b43e8dd14ecd03).
